server:
  port: 8888
  servlet:
    context-path: /auth

spring:
  application:
    name: shop-auth

  datasource:
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf-8&isSSL=false
    username: root
    password: root


  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        namespace: fd665b49-1c10-4f45-9abd-35f39854b74f
      discovery:
        namespace: fd665b49-1c10-4f45-9abd-35f39854b74f

  config:
    import:
      - nacos:auth.yml


logging:
  level:
    org.springframework.security: trace