version: '3.8'

services:

  redis:
    container_name: redis-local
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  mysql:
    container_name: mysql-local
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shop
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  # 注意：自定义db需要初始化schema(https://github.com/nacos-group/nacos-docker/issues/121)
  nacos:
    container_name: nacos-local
    image: nacos/nacos-server
    environment:
      PREFER_HOST_MODE: hostname
      MODE: standalone
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: mysql-local
      MYSQL_SERVICE_DB_NAME: nacos
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: root
      MYSQL_SERVICE_DB_PARAM: useUnicode=true&characterEncoding=utf-8&isSSL=false
    ports:
      - "8848:8848"
      - "9848:9848"
    depends_on:
      - mysql

    # RocketMQ
  rmq_ns:
    image: apache/rocketmq:5.3.1
    container_name: rmq_ns
    ports:
      - "9876:9876"
    networks:
      - rocketmq
    command: sh mqnamesrv
  rmq_broker:
    image: apache/rocketmq:5.3.1
    container_name: rmq_broker
    ports:
      - "10909:10909"
      - "10911:10911"
      - "10912:10912"
    environment:
      - NAMESRV_ADDR=rmq_ns:9876
    depends_on:
      - rmq_ns
    networks:
      - rocketmq
    command: sh mqbroker
  rmq_proxy:
    image: apache/rocketmq:5.3.1
    container_name: rmq_proxy
    networks:
      - rocketmq
    depends_on:
      - rmq_broker
      - rmq_ns
    ports:
      - "8080:8080"
      - "8081:8081"
    restart: on-failure
    environment:
      - NAMESRV_ADDR=rmq_ns:9876
    command: sh mqproxy

volumes:
  mysql-data:
  redis-data:

networks:
  rocketmq:
    driver: bridge