server:
  port: 8080

spring:
  application:
    name: shop-gateway

  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        namespace: fd665b49-1c10-4f45-9abd-35f39854b74f
      discovery:
        namespace: fd665b49-1c10-4f45-9abd-35f39854b74f

  config:
    import:
      - nacos:gateway.yml


logging:
  level:
    org.springframework.cloud.gateway: debug